# Generated by Django 4.1.2 on 2024-07-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='company',
        ),
        migrations.AddField(
            model_name='services',
            name='company',
            field=models.ManyToManyField(related_name='portfolio', to='companies.companies'),
        ),
    ]
